# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
#       fail-fast: false
      matrix:
        coq-version:
          - 8.9.1
          - 8.12.1
          - 8.13.0
        include:
          - coq-version: 8.9.1
            ocaml-version: 4.09.1
          - coq-version: 8.12.1
            ocaml-version: 4.11.1
          - coq-version: 8.13.0
            ocaml-version: 4.11.1
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Use OCaml 4.11.1
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam pin add coq ${{ matrix.coq-version }}
          opam install dune angstrom ocamlgraph ppx_deriving
      - name: Build app
        run: opam exec -- dune build     
      - name: Generate source files
        run: ./generate.sh
      - name: Compile generated files 
        run: cd ./case-studies/examples && make

          
          
          
          
          
          
          
          
